package vigor

import "github.com/tanema/gween/ease"

var (
	easeFuncMappings = map[string]ease.TweenFunc{
		"Linear":       ease.Linear,
		"InQuad":       ease.InQuad,
		"OutQuad":      ease.OutQuad,
		"InOutQuad":    ease.InOutQuad,
		"OutInQuad":    ease.OutInQuad,
		"InCubic":      ease.InCubic,
		"OutCubic":     ease.OutCubic,
		"InOutCubic":   ease.InOutCubic,
		"OutInCubic":   ease.OutInCubic,
		"InQuart":      ease.InQuart,
		"OutQuart":     ease.OutQuart,
		"InOutQuart":   ease.InOutQuart,
		"OutInQuart":   ease.OutInQuart,
		"InQuint":      ease.InQuint,
		"OutQuint":     ease.OutQuint,
		"InOutQuint":   ease.InOutQuint,
		"OutInQuint":   ease.OutInQuint,
		"InExpo":       ease.InExpo,
		"OutExpo":      ease.OutExpo,
		"InOutExpo":    ease.InOutExpo,
		"OutInExpo":    ease.OutInExpo,
		"InSine":       ease.InSine,
		"OutSine":      ease.OutSine,
		"InOutSine":    ease.InOutSine,
		"OutInSine":    ease.OutInSine,
		"InCirc":       ease.InCirc,
		"OutCirc":      ease.OutCirc,
		"InOutCirc":    ease.InOutCirc,
		"OutInCirc":    ease.OutInCirc,
		"InBack":       ease.InBack,
		"OutBack":      ease.OutBack,
		"InOutBack":    ease.InOutBack,
		"OutInBack":    ease.OutInBack,
		"InBounce":     ease.InBounce,
		"OutBounce":    ease.OutBounce,
		"InOutBounce":  ease.InOutBounce,
		"OutInBounce":  ease.OutInBounce,
		"InElastic":    ease.InElastic,
		"OutElastic":   ease.OutElastic,
		"InOutElastic": ease.InOutElastic,
		"OutInElastic": ease.OutInElastic,
	}
)
